listening-port=3478
fingerprint
lt-cred-mech

realm=call.elcsa.online
server-name=call.elcsa.online

user=turnuser:strongpassword123

total-quota=100
stale-nonce
no-multicast-peers

external-ip=185.255.132.103